<?php if (!defined('BASEPATH'))
    exit('No direct script access allowed');
/*
<!-- .................................. -->
<!-- ...........COPYRIGHT ............. -->
<!-- Authors : Hisyam Husein .......... -->
<!-- Email : hisyam.husein@gmail.com .. -->
<!-- About : hisyam.ismul.com ......... -->
<!-- Instagram : @hisyambsa............ -->
<!-- .................................. -->
*/
class wo_Admin_model extends CI_Model
{

    public $table = 'admin';
    public $id = 'id_admin';
    public $order = 'ASC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->join('akses', 'akses.id_akses = admin.id_akses');
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        $this->db->join('akses', 'akses.id_akses = admin.id_akses');
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_admin', $q);
	$this->db->or_like('username', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('password', $q);
	$this->db->or_like('created', $q);
	$this->db->or_like('last_login', $q);
	$this->db->or_like('akses.id_akses', $q);
    $this->db->join('akses', 'akses.id_akses = admin.id_akses');
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_admin', $q);
	$this->db->or_like('username', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('password', $q);
	$this->db->or_like('created', $q);
	$this->db->or_like('last_login', $q);
	$this->db->or_like('akses.id_akses', $q);
    $this->db->join('akses', 'akses.id_akses = admin.id_akses');
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file wo_User_model.php */
/* Location: ./application/models/wo_User_model.php */
/* Please DO NOT modify this information : */
/* Generated by Hisyam 2018-11-03 16:07:17 */
/* http://hisyam.ismul.com.com */